---
# tasks file for ansible-role-git-repository

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ git_repository_log_dir }}"
    mode: 0755
    owner: "{{ git_repository_user }}"
    group: "{{ git_repository_group }}"
    state: directory
  notify: Restart git_repository

- name: Create db directory
  file:
    path: "{{ git_repository_db_dir }}"
    mode: 0755
    owner: "{{ git_repository_user }}"
    group: "{{ git_repository_group }}"
    state: directory
  notify: Restart git_repository

- name: Create git_repository.conf
  template:
    src: git_repository.conf.j2
    dest: "{{ git_repository_conf_file }}"
    validate: echo %s
  notify: Restart git_repository

- name: Start git_repository
  service:
    name: "{{ git_repository_service }}"
    enabled: true
    state: started
